### ISSUE TITLE
Link counts per article

### ISSUE THREAD

**Issue by fgnievinski** [BrandonXLF/linkcount#34]
Thank you for your excellent Link count tool:
https://linkcount.toolforge.org/?project=en.wikipedia.org&page=Template%3AIETF+RFC

Would it be possible to extend the tool and report the transclusion count per page, please?

Background: I'm interesting in finding the articles that make heavy use of Template:IETF RFC. 

Ranking the top-10 articles with the most calls ("transclusions"?) of that template, would suffice.

**Comment by BrandonXLF** [comment]
I'm glad you are enjoying the tool!

Unfortunately, the behaviour you want is not achievable using the methods this tool uses. The tool currently gets the numbers it reports from the database without looking at any page content, whereas to get the transaction count per page would require parsing the content of each page.

However, it seems like https://bambots.brucemyers.com/TemplateParam.php might be able to be modified to report the number of individual transclusions per page since it already lists the total number of individual transclusions.

**Comment by BrandonXLF** [comment]
I believe the relevant GitHub repos are https://github.com/bamyers99/Bambots and https://github.com/bamyers99/MWDumpTemplateParser
